// File auto-generated by ReleaseAutomation.  Please see PackageInfo.txt for version and name changes.
namespace DG.Tweening
{
    public static partial class PackageInfo
    {
        public const string PackageName = "DG.Tweening";
        public const string PackageVersion = "1.0.2";
    }
}